# -*- coding: utf-8 -*-
"""E-Commerce-Sales-Analysis jupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKVQlBSr6K2v5neYXdzR2zrcq6W9oOi_

**Project: E-Commerce Sales Analysis**
"""

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir('/content'))

import zipfile
with zipfile.ZipFile('/content/archive.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/data')

import os
print(os.listdir('/content/data'))

**LOAD THE DATASET**
import pandas as pd
df =pd.read_csv('/content/data/SampleSuperstore.csv')
df.head()

**Check for missing values**
df.isnull().sum()

**Total Sales**
print(df["Sales"].sum())

df.shape

df.columns

df.info()

## Question 1 : What is the Overall Business Performance?

### Objective
Calculate the total sales, total profit, and total quantity sold to understand the
overall business performance.

### Solution
print("Total sales:", df['Sales'].sum())
print("Total Profit:", df['Profit'].sum())
print("Total Quanity:",
df['Quantity'].sum())

## Question 2: Which Product Category Generates the highest Sales?

### Objective
Identify the product category that contributes the highest sales revenue to the business.

### Solution
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

## Question 3: Which States Contribute the Most to Overall Sales?

## Objective
Analyze sales across different states to identify the top-performing states.

## Solution
df.groupby('State')['Sales'].sum().sort_values(ascending=False).head(10)

## Question 4: Which Cities Generate the Highest Profit?

### Objective
Determine the cities that contribute the most to profit and evaluate their business performance.

### Solution
df.groupby('City')['Profit'].sum().sort_values(ascending=False).head(10)

## Question 5: Which Product Category is the Most Profitable?

## Objective
Compare prrofit across product categories to identify the category generating the highest profit.

## Solution
df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

"""#Data Visualization

###Objective
Visualize sales and profit trends across different categories and regions to gain better buiness insights.
"""

import matplotlib.pyplot as plt
df.groupby('Category')['Sales'].sum().plot(kind='bar')
plt.title('Sales by Category')
plt.ylabel('Sales')
plt.show()

df.groupby('Category')['Profit'].sum().plot(kind='bar')
plt.title('Profit by Category')
plt.ylabel('Profit')
plt.show()

df.groupby('State')['Sales'].sum().sort_values(ascending=False).head(10).plot(kind='bar')
plt.title('Sales by State')
plt.ylabel('Top 10 States by Sales')
plt.show()

# Conclusion
- Technology is the best-performing category in terms of sales and profit.
- California contributes the highest sales.
- New York City generates the highest profit.
- Furniture has high sales but relatively low profit.